export default {
  searchShowBtn:false,
  saveBtn: false,
  updateBtn: false,
  cancelBtn: false,
  menu: false,
  addBtn: false,
  delBtn: false,
  editBtn: false,
  dialogDrag: true,
  searchBtn: false,
  emptyBtn: false,
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  viewBtn: true,
  selection: true,
  dialogClickModal: false,
  column: [
    {
      label:'序号',
      prop:'index',
      fixed:true,
      width: 70,
      display: false,
      align: "center"
    },
    {
      label: "主键",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: 'tenantId',
              hide: true, display: false, addDisplay: false, editDisplay: false, viewDisplay: false, search: false,
      hide: true, display: false, addDisplay: false, editDisplay: false, viewDisplay: false, search: false,
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "备注",
      prop: "remark",
      type: "input",
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "状态",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "表名称",
      prop: "tableName",
      type: "input",
    },
    {
      label: "表注释",
      prop: "tableComment",
      type: "input",
    },
    {
      label: "数据库链接",
      prop: "databaseId",
      type: "input",
    },
    {
      label: "用途",
      prop: "purpose",
      type: "input",
    },
  {
      label: '附件列表',
      span: 24,
      width: "100",
      prop: 'uploadList',
      slot: true,
      display: false,
    },
  ]
}
