export default {
  searchShowBtn:false,
  saveBtn: false,
  updateBtn: false,
  cancelBtn: false,
  menu: false,
  addBtn: false,
  delBtn: false,
  editBtn: false,
  dialogDrag: true,
  searchBtn: false,
  emptyBtn: false,
  height:'auto',
  calcHeight: 30,
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  viewBtn: true,
  selection: true,
  formLabelWidth: 120,
  dialogClickModal: false,
  column: [
    {
      label:'序号',
      prop:'index',
      fixed:true,
      width: 70,
      display: false,
      align: "center"
    },
    {
      label: "编号",
      prop: "id",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "通知标题",
      prop: "noticeTitle",
      type: "input",
      search: true,
    },
    {
      label: "通知内容",
      prop: "noticeContent",
      type: "input",
      hide: true,
      component: "AvueUeditor",
      options: {
        action: "/api/blade-resource/oss/endpoint/put-file",
        props: {
          res: "data",
          url: "link",
        },
      },
    },
    {
      label: "通知状态",
      width: 80,
      prop: "noticeStatus",
      type: "select",
      dicData: [{label: "关闭", value: 2,}, {label: "正常", value: 1,}]
    },
    {
      label: "发送频率",
      width: 100,
      prop: "sendRate",
      search: true,
      type: "select",
      dicMethod: "post",
            dicUrl: "/api/blade-system/dict-biz/dictionary?code=notice_frequency",
      props: {
        label: 'dictValue',
        value: 'dictKey'
      },
    },
    {
      label: "发送类型",
      prop: "sendType",
      width: 100,
      search: true,
      type: "tree",
      dicMethod: "post",
            dicUrl: "/api/blade-system/dict-biz/dictionary-tree?code=notice_type",
      props: {
        label: 'dictValue',
        value: 'dictKey'
      },
      rules: [
        { required: true, message: "请选择消息类型", trigger: "change" },
      ],
      dicFormatter: (res) => {
        let data = res.data
        for (let i = 0; i < data.length; i++) {
          data[i].disabled = true
        }
        return data
      },
    },
    {
      label: "首次发送时间",
      prop: "sentTime",
      type: "date",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
    },
    {
      label: "截至发送时间",
      prop: "endSentTime",
      type: "date",
      format: "yyyy-MM-dd hh:mm:ss",
      valueFormat: "yyyy-MM-dd hh:mm:ss",
    },
    {
      label: "创建人",
      prop: "createUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建部门",
      prop: "createDept",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "创建时间",
      prop: "createTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改人",
      prop: "updateUser",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "修改时间",
      prop: "updateTime",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    // {
    //   label: "备注",
    //   prop: "remark",
    //   type: "input",
    // },
    {
      label: "状态",
      prop: "status",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "是否已删除",
      prop: "isDeleted",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "租户ID",
      prop: 'tenantId',
              hide: true, display: false, addDisplay: false, editDisplay: false, viewDisplay: false, search: false,
      hide: true, display: false, addDisplay: false, editDisplay: false, viewDisplay: false, search: false,
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "链接",
      prop: "href",
      type: "input",
      width: 200,
      slot: true,
      overHidden: true,
    },
    {
      label: "关联数据id",
      prop: "fromId",
      type: "input",
      addDisplay: false,
      editDisplay: false,
      viewDisplay: false,
      hide: true,
    },
    {
      label: "发送目标",
      prop: "targetName",
      hide: true,
      type: "input",
    },
  {
      label: '附件列表',
      span: 24,
      width: "100",
      prop: 'uploadList',
      slot: true,
      display: false,
    },
  ]
}
