<template><basic-container><el-card shadow="never">
  <div class="filters"><el-input v-model="query.keyword" clearable placeholder="事件编号、摘要或发起人" @keyup.enter="search"/><el-select v-model="query.status" clearable placeholder="全部状态"><el-option label="进行中" value="ACTIVE"/><el-option label="已停止" value="STOPPED"/><el-option label="已完成" value="COMPLETED"/></el-select><el-button type="primary" @click="search">查询</el-button></div>
  <el-table :data="page.records" v-loading="loading" stripe>
    <el-table-column prop="eventNo" label="事件编号" width="190"/><el-table-column prop="eventSummary" label="事件摘要" min-width="240" show-overflow-tooltip/><el-table-column prop="latestFact" label="最新进展" min-width="220" show-overflow-tooltip><template #default="{row}">{{ row.latestFact||'暂无反馈' }}</template></el-table-column><el-table-column prop="creatorName" label="发起人" width="120"/>
    <el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.eventStatus==='ACTIVE'?'success':'info'">{{ statusText(row.eventStatus) }}</el-tag></template></el-table-column>
    <el-table-column prop="recipientCount" label="接收人" width="80"/><el-table-column prop="activeBranchCount" label="活跃分支" width="90"/><el-table-column prop="evaluationCount" label="AI评估" width="80"/><el-table-column prop="notificationCount" label="通知" width="70"/>
    <el-table-column prop="eventTime" label="事件时间" width="180"/><el-table-column prop="createTime" label="创建时间" width="180"/>
  </el-table><el-pagination class="pager" background layout="total, sizes, prev, pager, next" :total="page.total" v-model:current-page="query.page" v-model:page-size="query.size" @change="load"/>
</el-card></basic-container></template>
<script setup>import{onMounted,reactive,ref}from'vue';import{getAdminEvents}from'@/api/smartReminder';const loading=ref(false),query=reactive({page:1,size:20,keyword:'',status:''}),page=reactive({records:[],total:0});const statusText=v=>({ACTIVE:'进行中',STOPPED:'已停止',COMPLETED:'已完成'}[v]||v);const load=async()=>{loading.value=true;try{Object.assign(page,(await getAdminEvents(query)).data.data||{});}finally{loading.value=false;}};const search=()=>{query.page=1;load();};onMounted(load);</script>
<style scoped>.filters{display:flex;gap:10px;margin-bottom:16px}.filters .el-input{width:300px}.filters .el-select{width:150px}.pager{justify-content:flex-end;margin-top:18px}</style>
