<template>
  <AppShell :title="mt('好友')" :subtitle="mt('只能提醒已相互确认的好友')">
    <div class="search"><input v-model.trim="keyword" class="sr-input" :placeholder="mt('账号、姓名或手机号')" @keyup.enter="search"/><button class="sr-button" @click="search">{{ mt("查找") }}</button></div>
    <section v-if="results.length" class="sr-card"><h3>{{ mt("查找结果") }}</h3><div v-for="user in results" :key="user.id" class="person"><div class="sr-avatar">{{ initial(user) }}</div><div><b>{{ display(user) }}</b><p>{{ user.account }} · {{ user.phone||mt('未留手机') }}</p></div><button v-if="user.relationStatus==='NONE'" class="sr-button secondary" @click="add(user)">{{ mt("添加") }}</button><span v-else class="relation">{{ mt(relation(user.relationStatus)) }}</span></div></section>
    <section v-if="requests.incoming?.length" class="sr-card"><h3>{{ mt("待处理申请") }}</h3><div v-for="item in requests.incoming" :key="item.id" class="person"><div class="sr-avatar">{{ initial(item) }}</div><div><b>{{ display(item) }}</b><p>{{ item.requestMessage||mt('请求添加你为好友') }}</p></div><div class="reply"><button @click="reply(item.id,false)">{{ mt("拒绝") }}</button><button @click="reply(item.id,true)">{{ mt("同意") }}</button></div></div></section>
    <h3 class="title">{{ mt("我的好友·") }}{{ friends.length }}</h3><div v-if="!friends.length" class="sr-empty">{{ mt("暂无好友，可以从上方查找") }}</div>
    <section v-for="user in friends" :key="user.id" class="sr-card person"><div class="sr-avatar">{{ initial(user) }}</div><div><b>{{ display(user) }}</b><p>{{ user.account }} · {{ user.phone||mt('未留手机') }}</p></div></section>
  </AppShell>
</template>
<script setup>
import {mt} from './mobileLocale';
import { onMounted,reactive,ref } from 'vue';import { ElMessage } from 'element-plus';import AppShell from './AppShell.vue';import {getFriends,getFriendRequests,replyFriend,requestFriend,searchUsers} from '@/api/smartReminder';
const keyword=ref(''),results=ref([]),friends=ref([]),requests=reactive({incoming:[],outgoing:[]});const display=u=>u.friendRemark||u.name||u.realName||u.account;const initial=u=>(display(u)||'?').slice(0,1);const relation=s=>({FRIEND:'已是好友',PENDING_OUT:'已申请',PENDING_IN:'待你同意'}[s]||s);const load=async()=>{friends.value=(await getFriends()).data.data||[];Object.assign(requests,(await getFriendRequests()).data.data||{});};const search=async()=>{if(!keyword.value)return;results.value=(await searchUsers(keyword.value)).data.data||[];};const add=async u=>{await requestFriend({targetUserId:u.id,message:'我想添加你为智能提醒好友'});ElMessage.success(mt('好友申请已发送'));await search();};const reply=async(id,accept)=>{await replyFriend({requestId:id,accept});ElMessage.success(accept?'已成为好友':'已拒绝');await load();};onMounted(load);
</script>
<style scoped>.search{display:grid;grid-template-columns:1fr auto;gap:8px;margin-bottom:14px}.person{display:flex;align-items:center;gap:11px}.person+.person{border-top:1px solid #edf0f5;padding-top:13px;margin-top:13px}.person>div:nth-child(2){flex:1;min-width:0}.person p{margin:3px 0}.person .sr-button{min-height:36px;padding:0 12px}.relation{font-size:12px;color:#8a92a3}.reply{display:flex!important;gap:5px!important;flex:0 0 auto!important}.reply button{border:0;border-radius:9px;padding:8px;color:#7c8495}.reply button:last-child{background:#315bff;color:#fff}.title{font-size:15px;margin:22px 4px 10px}</style>
