async page => {
 const checks=[], errors=[];page.on('pageerror',e=>errors.push(e.message));
 let rows=[], revision=0, job='NOT_FOUND', submitted=null, extraction='FAILED', confirmCalls=[];
 const candidate={id:'candidate-message',messageRole:'assistant',messageType:'CANDIDATE',content:'请确认安排',payload:{candidateId:'parity-c1',events:[{summary:'明天审核合同',timeDescription:'明天10点',eventTime:'2026-09-21 10:00:00',firstEvaluateTime:'2026-09-21 09:00:00',recipients:[{friendRemark:'',name:'陈通',account:'test'}]}]}};
 const fulfill=(r,data)=>r.fulfill({json:{code:200,data}});
 await page.route('**/api/app/reminder/chat/messages**',r=>fulfill(r,rows));
 await page.route('**/api/app/reminder/chat/sync**',r=>fulfill(r,{revision:String(revision),messages:rows}));
 await page.route('**/api/app/reminder/files/upload',r=>fulfill(r,{id:'file-1',extractStatus:extraction,extractMessage:'无法解析这个文档'}));
 await page.route('**/api/app/reminder/chat/jobs/**',r=>{if(r.request().url().includes('/submit')){submitted=JSON.parse(r.request().postData());job='RUNNING';}return fulfill(r,{status:job,streamSupported:false,reasoning:job==='RUNNING'?'正在分析你的安排':''});});
 let stopAllowed=false;await page.route('**/api/app/reminder/chat/stop',r=>{if(stopAllowed)job='CANCELLED';return fulfill(r,{stopped:stopAllowed});});
 await page.route('**/api/app/reminder/candidate/confirm',r=>{const body=JSON.parse(r.request().postData());confirmCalls.push(body);if(confirmCalls.length===1){candidate.payload.events[0].scheduleConflicts=[{summary:'已有安排'}];rows=[candidate];revision++;return fulfill(r,{confirmationRequired:true});}candidate.messageType='CANDIDATE_CONFIRMED';return fulfill(r,{eventIds:[]});});
 await page.route('**/api/app/reminder/chat/context/clear',r=>{rows=[];revision++;return fulfill(r,{});});
 await page.goto('http://localhost:5174/#/pages/chat/index');await page.locator('.compose-input textarea').waitFor();
 const addDocument=async()=>{await page.locator('.compose-action').first().click();await page.evaluate(()=>{const original=HTMLInputElement.prototype.click;HTMLInputElement.prototype.click=function(){if(this.type==='file'){const dt=new DataTransfer();dt.items.add(new File(['contract'],'合同.txt',{type:'text/plain'}));this.files=dt.files;this.dispatchEvent(new Event('change'));HTMLInputElement.prototype.click=original;}else original.call(this);};});await page.getByText('选择文档',{exact:true}).click();};
 await addDocument();await page.getByText('重试',{exact:true}).waitFor();if((await page.locator('.send').getAttribute('disabled'))!=='true')throw Error('Failed extraction allowed send');checks.push('文件有ID但解析失败不能发送');
 extraction='SUCCESS';await page.getByText('重试',{exact:true}).click();await page.waitForFunction(()=>document.querySelector('.file')?.textContent.includes('已就绪'));
 await page.locator('.compose-input textarea').fill('提醒我看附件');await page.locator('.send').click();await page.waitForTimeout(1300);if(submitted?.fileIds?.[0]!=='file-1')throw Error('Missing fileId');await page.getByText('附件：合同.txt',{exact:true}).waitFor();checks.push('文档选择重试和附件名保留');
 rows=[{id:'notice-new',messageRole:'assistant',messageType:'REMINDER',content:'生成期间收到的新提醒',eventId:'201'}];revision++;await page.getByText('生成期间收到的新提醒',{exact:true}).waitFor({timeout:12000});if(!await page.locator('.send-busy').count())throw Error('Sync removed running reply');checks.push('生成期间同步新提醒且保留当前回复');
 await page.locator('.send-busy').click();await page.locator('.top-tip').filter({hasText:'无法撤回'}).waitFor();stopAllowed=true;await page.locator('.send-busy').click();await page.locator('.send-busy').waitFor({state:'hidden'});checks.push('停止按钮尊重服务端确认');
 rows=[candidate];revision++;await page.getByText('确认创建',{exact:true}).waitFor({timeout:12000});await page.getByText('确认创建',{exact:true}).click();await page.getByText('仍要安排',{exact:true}).waitFor();await page.waitForTimeout(500);if(confirmCalls.length!==1||confirmCalls[0].acceptConflicts!==false)throw Error('New conflict resubmitted without card review');await page.getByText('仍要安排',{exact:true}).click();await page.getByText('已创建',{exact:true}).waitFor();if(confirmCalls[1].acceptConflicts!==true)throw Error('Conflict acceptance missing');checks.push('新增冲突先刷新卡片再人工确认');
 await page.locator('.compose-input textarea').fill('清除前的草稿');await addDocument();await page.waitForFunction(()=>document.querySelector('.file')?.textContent.includes('已就绪'));await page.locator('.toolbar').last().click();await page.getByText('确认清除',{exact:true}).click();await page.locator('.mask').waitFor({state:'hidden'});if(await page.locator('.compose-input textarea').inputValue()||await page.locator('.file').count())throw Error('Clear retained composer');checks.push('清除上下文同步清空草稿附件');
 await page.locator('.compose-input textarea').evaluate(el=>{const transfer=new DataTransfer();transfer.items.add(new File(['image'],'paste.png',{type:'image/png'}));el.dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));});await page.waitForFunction(()=>document.querySelector('.file')?.textContent.includes('paste.png'));checks.push('粘贴图片上传');
 await page.screenshot({path:'output/playwright/chat-parity.png'});
 if(errors.length)throw Error(errors.join(';'));return {checks,errors};
}
